default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: exercise2_development
test:
  <<: *default
  database: exercise2_test
production:
  <<: *default
  database: exercise2_production
  username: exercise2
  password: <%= ENV['EXERCISE2_DATABASE_PASSWORD'] %>
